CREATE DATABASE ZOMATO;
USE ZOMATO;
SHOW TABLES FROM ZOMATO;

SELECT * FROM CUSTOMERS;
DESCRIBE CUSTOMERS;
ALTER TABLE CUSTOMERS
MODIFY COLUMN CUSTOMER_ID INT PRIMARY KEY,
MODIFY COLUMN NAME VARCHAR(35),
MODIFY COLUMN EMAIL VARCHAR(50),
MODIFY COLUMN PHONE VARCHAR(15),
MODIFY COLUMN LOCATION VARCHAR(500),
MODIFY COLUMN SIGNUP_DATE DATE,
MODIFY COLUMN PREFERRED_CUISINE VARCHAR(20),
MODIFY COLUMN TOTAL_ORDERS INT,
MODIFY COLUMN AVERAGE_RATING DECIMAL(4,2);
SELECT * FROM CUSTOMERS;

SELECT * FROM DELIVERIES;
DESCRIBE DELIVERIES;
ALTER TABLE DELIVERIES
MODIFY COLUMN DELIVERY_ID INT PRIMARY KEY,
MODIFY COLUMN ORDER_ID INT,
MODIFY COLUMN DELIVERY_PERSON_ID INT,
MODIFY COLUMN DELIVERY_STATUS VARCHAR(30),
MODIFY COLUMN DISTANCE DECIMAL(5,2),
MODIFY COLUMN DELIVERY_TIME INT,
MODIFY COLUMN ESTIMATED_TIME INT,
MODIFY COLUMN DELIVERY_FEE DECIMAL(7,2),
MODIFY COLUMN VEHICLE_TYPE VARCHAR(30);

SELECT * FROM DELIVERY_PERSONS;
ALTER TABLE DELIVERY_PERSONS
MODIFY COLUMN DELIVERY_PERSON_ID INT PRIMARY KEY,
MODIFY COLUMN NAME VARCHAR(50),
MODIFY COLUMN CONTACT_NUMBER VARCHAR(20),
MODIFY COLUMN VEHICLE_TYPE VARCHAR(20),
MODIFY COLUMN TOTAL_DELIVERIES INT,
MODIFY COLUMN AVERAGE_RATING DECIMAL(5,2),
MODIFY COLUMN LOCATION VARCHAR(100);

SELECT  * FROM RESTAURANTS;
ALTER TABLE RESTAURANTS
MODIFY COLUMN RESTAURANT_ID INT PRIMARY KEY,
MODIFY COLUMN NAME VARCHAR(50),
MODIFY COLUMN CUISINE_TYPE VARCHAR(50),
MODIFY COLUMN LOCATION VARCHAR(100),
MODIFY COLUMN OWNER_NAME VARCHAR(50),
MODIFY COLUMN AVERAGE_DELIVERY_TIME INT,
MODIFY COLUMN CONTACT_NUMBER VARCHAR(15),
MODIFY COLUMN RATING DECIMAL(5,2),
MODIFY COLUMN TOTAL_ORDERS INT,
MODIFY COLUMN IS_ACTIVE INT;

SELECT * FROM ORDERS;
ALTER TABLE ORDERS
ADD COLUMN ORDER_DATED DATE,
ADD COLUMN ORDER_TIME TIME;

SET SQL_SAFE_UPDATES = 0;
UPDATE ORDERS
SET 
    ORDER_DATED = DATE(ORDER_DATE),
    ORDER_TIME = TIME(ORDER_DATE);

SET SQL_SAFE_UPDATES = 1;

SELECT * FROM ORDERS;

ALTER TABLE ORDERS
MODIFY COLUMN ORDER_DATED DATE AFTER RESTAURANT_ID;

ALTER TABLE ORDERS
MODIFY COLUMN ORDER_TIME TIME AFTER ORDER_DATED;

ALTER TABLE ORDERS
DROP COLUMN ORDER_DATE;

SELECT * FROM ORDERS;
ALTER TABLE ORDERS
RENAME COLUMN ORDER_DATED TO ORDER_DATE;

SELECT * FROM ORDERS;

ALTER TABLE ORDERS
ADD COLUMN DELIVERY_DATE DATE,
ADD COLUMN DELIVERY_TIMES TIME;

SET SQL_SAFE_UPDATES = 0;
UPDATE ORDERS
SET 
	DELIVERY_DATE = DATE(DELIVERY_TIME),
    DELIVERY_TIMES = TIME(DELIVERY_TIME);
    
SET SQL_SAFE_UPDATES = 1;

SELECT * FROM ORDERS;

SET SQL_SAFE_UPDATES = 1;

ALTER TABLE ORDERS
DROP COLUMN DELIVERY_TIME;

SELECT * FROM ORDERS;

ALTER TABLE ORDERS
MODIFY COLUMN DELIVERY_DATE DATE AFTER ORDER_TIME;
ALTER TABLE ORDERS
MODIFY COLUMN DELIVERY_TIMES TIME AFTER DELIVERY_DATE;


SELECT * FROM ORDERS;

DESCRIBE ORDERS;

ALTER TABLE ORDERS
MODIFY COLUMN ORDER_ID INT PRIMARY KEY,
MODIFY COLUMN CUSTOMER_ID INT,
MODIFY COLUMN RESTAURANT_ID INT,
MODIFY COLUMN STATUS VARCHAR(20),
MODIFY COLUMN TOTAL_AMOUNT DECIMAL(10,2),
MODIFY COLUMN PAYMENT_MODE VARCHAR(20),
MODIFY COLUMN DISCOUNT_APPLIED DECIMAL(5,2),
MODIFY COLUMN FEEDBACK_RATING DECIMAL(5,2);

ALTER TABLE ORDERS
ADD CONSTRAINT FK_CUSTOMER_ID
FOREIGN KEY (CUSTOMER_ID)
REFERENCES CUSTOMERS(CUSTOMER_ID);

ALTER TABLE ORDERS
ADD CONSTRAINT FK_RESTAURANT_ID
FOREIGN KEY (RESTAURANT_ID)
REFERENCES RESTAURANTS(RESTAURANT_ID);

DESCRIBE ORDERS;

DESCRIBE DELIVERIES;

ALTER TABLE DELIVERIES
ADD CONSTRAINT FK_ORDER_ID
FOREIGN KEY (ORDER_ID)
REFERENCES ORDERS(ORDER_ID);

ALTER TABLE DELIVERIES
ADD CONSTRAINT FK_DELIVERY_PERSON_ID
FOREIGN KEY (DELIVERY_PERSON_ID)
REFERENCES DELIVERY_PERSONS(DELIVERY_PERSON_ID);

DESCRIBE RESTAURANTS;

describe orders;

SELECT * FROM ORDERS;
SELECT STATUS,COUNT(STATUS) AS COUNT FROM ORDERS
GROUP BY STATUS;

-- 1.Which customers generate the highest revenue?
SELECT C.CUSTOMER_ID AS CUSTOMER_ID,
		C.NAME AS CUSTOMER_NAME ,
		ROUND(SUM(O.TOTAL_AMOUNT),2) AS REVENUE_GENERATED,
		round(AVG(O.TOTAL_AMOUNT),2) AS AVERAGE_AMOUNT,
		COUNT(O.ORDER_ID) AS ORDER_COUNT
FROM ORDERS O 
JOIN CUSTOMERS C
ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE O.STATUS = "DELIVERED"
GROUP BY C.CUSTOMER_ID,C.NAME
ORDER BY REVENUE_GENERATED DESC
LIMIT 5;
-- Customer 436 generated the highest revenue of ₹13,845.66 from 5 delivered orders, with an average order value of ₹2,769.13.


-- 2.Who are the top 10 customers by number of orders?
SELECT  C.CUSTOMER_ID AS CUSTOMER_ID,
		C.NAME AS CUSTOMER_NAME,
        COUNT(ORDER_ID) AS ORDERS_COUNT
FROM ORDERS O
JOIN CUSTOMERS C
ON O.CUSTOMER_ID=C.CUSTOMER_ID
WHERE O.STATUS = "DELIVERED"
GROUP BY C.CUSTOMER_ID,C.NAME
ORDER BY ORDERS_COUNT DESC
LIMIT 10;
-- The most active customers were Customer IDs 227,92 AND 436.
-- Also customer_id 436 appeared in top 1 highest revenue generate list with frequently orders

-- 3.Which customers have high order frequency but low spending?
SELECT  C.CUSTOMER_ID AS CUSTOMER_ID,
		C.NAME AS CUSTOMER_NAME,
		COUNT(O.ORDER_ID) AS ORDER_COUNT,
        ROUND(SUM(O.TOTAL_AMOUNT),2) AS AMOUNT
FROM CUSTOMERS C 
JOIN ORDERS O 
ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE O.STATUS = 'DELIVERED'
GROUP BY C.CUSTOMER_ID,C.NAME
ORDER BY ORDER_COUNT DESC,AMOUNT ASC
LIMIT 5;
-- Customer_id 92 have high frequency in ordering but customer is low spending.We can attract her with more campaigns
-- Cutsomer_id 436 stand outs again with high frequency of orders with high revenue along side with customer_id 227
         
-- 4.Which premium customers generate the most revenue?
SELECT * FROM CUSTOMERS;
SELECT  C.CUSTOMER_ID AS CUSTOMER_ID,
		C.NAME AS CUSTOMER_NAME,
        COUNT(O.ORDER_ID) AS COUNT_ORDERS,
        SUM(O.TOTAL_AMOUNT) AS REVENUE_GENERATED
FROM CUSTOMERS C 
JOIN ORDERS O 
ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE O.STATUS = 'DELIVERED'
AND   C.IS_PREMIUM = 1
GROUP BY C.CUSTOMER_ID,C.NAME
ORDER BY REVENUE_GENERATED DESC
LIMIT 5;
-- Customer_id 436 being our regular and high revenue generating customer among all the customers.
SELECT MAX(ORDER_DATE) FROM ORDERS;

-- 5.Identify customers whose order frequency has declined significantly over time.
WITH CUSTOMERS_BEHAVIOUR AS(
		SELECT  C.CUSTOMER_ID AS CUSTOMER_ID,
				C.NAME AS CUSTOMER_NAME,
                COUNT(CASE WHEN O.ORDER_DATE >= DATE('2025-07-12') - interval 1 YEAR
                      THEN 1 END) AS RECENT_ORDERS,
				COUNT(CASE WHEN O.ORDER_DATE < DATE('2025-07-12') - interval 1 YEAR
					  THEN 1 END ) AS OLD_ORDERS
				FROM ORDERS O JOIN CUSTOMERS C
				ON O.CUSTOMER_ID = C.CUSTOMER_ID
                WHERE O.STATUS = "DELIVERED"
                GROUP BY C.CUSTOMER_ID,C.NAME
)
SELECT * FROM CUSTOMERS_BEHAVIOUR
WHERE OLD_ORDERS > RECENT_ORDERS
ORDER BY (OLD_ORDERS -  RECENT_ORDERS) DESC;
-- Customer_id 464,303,266,223 didnot order any orders in last 1 year

-- 6.What percentage of total revenue comes from premium customers versus regular customers?
SELECT
    C.IS_PREMIUM,
    ROUND(
        SUM(O.TOTAL_AMOUNT) * 100 /
        (SELECT SUM(TOTAL_AMOUNT) FROM ORDERS),
        2
    ) AS REVENUE_PERCENTAGE
FROM CUSTOMERS C
JOIN ORDERS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE O.STATUS = 'DELIVERED'
GROUP BY C.IS_PREMIUM;

-- 7.Which restaurants generate the highest revenue despite having average ratings?(TOP 3)
SELECT  R.RESTAURANT_ID AS RESTAURANT_ID,
		R.NAME AS RESTAURANT_NAME,
		ROUND(SUM(O.TOTAL_AMOUNT),2) AS AMOUNT_GENERATED,
        ROUND(SUM(O.TOTAL_AMOUNT)/R.TOTAL_ORDERS,2) AS AVG_AMOUNT_PER_ORDER,
		R.CUISINE_TYPE AS CUISINE_TYPE,
		R.AVERAGE_DELIVERY_TIME AS AVG_DELIVERY_TIME,
		R.TOTAL_ORDERS AS TOTAL_ORDERS,
        R.RATING AS RATING
FROM ORDERS O JOIN RESTAURANTS R
ON R.RESTAURANT_ID=O.RESTAURANT_ID
WHERE R.IS_ACTIVE = 1 AND
	  R.RATING BETWEEN 2.00 AND 3.50 AND
      O.STATUS = 'DELIVERED'
GROUP BY R.RESTAURANT_ID,R.NAME
ORDER BY AMOUNT_GENERATED DESC;
--  AND R.AVERAGE_DELIVERY_TIME < 100
-- Out of 28 restaurants, 24 restaurants are having less avg_delivery_time(100).This indicates people are preferring more for fast deliveries than good rating.

-- 8.Which restaurants have excellent ratings but surprisingly low order volumes?
SELECT  O.RESTAURANT_ID AS RESTAURANT_ID,
		R.NAME AS RESTAURANT_NAME,
        SUM(O.TOTAL_AMOUNT) AS AMOUNT_GENERATED,
        COUNT(O.RESTAURANT_ID) AS TOTAL_ORDERS,
        R.RATING AS RATING,
        ROUND(SUM(O.TOTAL_AMOUNT)/COUNT(O.RESTAURANT_ID),2) AS AMOUNT_PER_ORDER,
        R.AVERAGE_DELIVERY_TIME AS AVG_DELIVERY_TIME
FROM RESTAURANTS R
 JOIN ORDERS O
ON R.RESTAURANT_ID = O.RESTAURANT_ID
WHERE   R.RATING > 4.25 
	AND O.STATUS = 'DELIVERED'
GROUP BY O.RESTAURANT_ID,R.NAME
ORDER BY TOTAL_ORDERS ASC;
-- These are the Restaurants generating less revenue desspite having excellent rating
-- Amount_per_order and Avg_delivery_time can be reasons for less revenue.

-- 9. Rank restaurants within each cuisine category based on revenue generated.
SELECT * FROM RESTAURANTS;
WITH CUISINE AS (
		SELECT  R.RESTAURANT_ID AS RESTAURANT_ID,
		R.NAME AS RESTAURANT_NAME,
        R.CUISINE_TYPE AS CUISINE_TYPE,
		ROUND(SUM(O.TOTAL_AMOUNT),2) AS REVENUE_GENERATED,
		RANK() OVER(PARTITION BY CUISINE_TYPE ORDER BY SUM(O.TOTAL_AMOUNT) DESC)RA
FROM RESTAURANTS R JOIN ORDERS O ON R.RESTAURANT_ID = O.RESTAURANT_ID
WHERE O.STATUS = 'DELIVERED' 
		AND R.IS_ACTIVE = 1
GROUP BY R.RESTAURANT_ID,R.NAME,R.CUISINE_TYPE)
		SELECT RESTAURANT_ID,
        RESTAURANT_NAME,
        CUISINE_TYPE,RA,REVENUE_GENERATED
FROM CUISINE
WHERE RA =1;
-- These are Restuarants Tops 1 in their respective Cuisine_type.

-- 10.Which restaurants receive the highest customer ratings while maintaining fast delivery times?

SELECT  R.RESTAURANT_ID AS RESTAURANT_ID,R.NAME AS RESTAURANT_NAME,
		ROUND(AVG(D.DELIVERY_TIME),2) AS AVG_DELIVERY_TIME_PER_ORDER,
        ROUND(AVG(FEEDBACK_RATING),2) AS AVG_FEEDBACK_RATING
        FROM RESTAURANTS R JOIN ORDERS O ON R.RESTAURANT_ID = O.RESTAURANT_ID
        JOIN DELIVERIES D ON O.ORDER_ID = D.ORDER_ID
        WHERE D.DELIVERY_STATUS = 'DELIVERED'
        AND R.IS_ACTIVE = 1
        GROUP BY R.RESTAURANT_ID,R.NAME
        HAVING AVG_DELIVERY_TIME_PER_ORDER < 30.00 
        AND AVG_FEEDBACK_RATING > 4.00
		ORDER BY AVG_DELIVERY_TIME_PER_ORDER ASC,
				 AVG_FEEDBACK_RATING DESC;
-- These restaurants maintain fast delivery times while achieving high customer ratings.
-- Savor Eatery (French) and Royal Eatery (Cafe) show the best balance between delivery speed and customer satisfaction.

-- 11.What percentage of total platform revenue is contributed by the top 5 restaurants?
WITH TOP_5 AS(
SELECT  O.RESTAURANT_ID,ROUND(SUM(O.TOTAL_AMOUNT),2) AS TOTAL_5
        FROM ORDERS O JOIN RESTAURANTS R ON R.RESTAURANT_ID = O.RESTAURANT_ID
        WHERE O.STATUS = 'DELIVERED'
		AND   R.IS_ACTIVE = 1
        GROUP BY O.RESTAURANT_ID)
SELECT ROUND(SUM(TOTAL_5)/(SELECT SUM(TOTAL_5) FROM TOP_5),2)*100 AS PERCENTAGE 
FROM (SELECT * FROM TOP_5
ORDER BY TOTAL_5 DESC
LIMIT 5) T;

-- Top 5 Restaurants are generating 14% of revenue from overall revenue

-- 12.Which delivery partners consistently complete deliveries faster than estimated time?
WITH CTE AS (SELECT  D.DELIVERY_PERSON_ID AS DELIVERY_PERSON_ID,
		DP.NAME AS DELIVERY_PERSON_NAME,
        COUNT(*) AS TOTAL_DELIVERIES,
        SUM(CASE WHEN DELIVERY_TIME < ESTIMATED_TIME THEN 1
		ELSE 0 END) AS COUNT
        FROM DELIVERIES D JOIN DELIVERY_PERSONS DP ON DP.DELIVERY_PERSON_ID = D.DELIVERY_PERSON_ID
		WHERE DELIVERY_STATUS = 'DELIVERED'
        GROUP BY D.DELIVERY_PERSON_ID,DP.NAME
        HAVING COUNT(*) > 2
        ORDER BY COUNT DESC,TOTAL_DELIVERIES DESC)
SELECT  DELIVERY_PERSON_ID,DELIVERY_PERSON_NAME,
		TOTAL_DELIVERIES,COUNT,
		ROUND((COUNT/TOTAL_DELIVERIES)*100,2) AS FASTER_DELIVERY_PERCENTAGE
        FROM CTE
        GROUP BY DELIVERY_PERSON_ID,DELIVERY_PERSON_NAME
        ORDER BY FASTER_DELIVERY_PERCENTAGE DESC,
				 TOTAL_DELIVERIES DESC
		LIMIT 5;

-- 13.Which delivery partners handle the highest workload while maintaining high ratings?
SELECT DELIVERY_PERSON_ID,NAME,TOTAL_DELIVERIES,AVERAGE_RATING FROM DELIVERY_PERSONS
WHERE AVERAGE_RATING >= 4.00
GROUP BY DELIVERY_PERSON_ID,NAME
ORDER BY TOTAL_DELIVERIES DESC,
		 AVERAGE_RATING DESC
         LIMIT 10;

-- 14.Which vehicle type provides the most efficient deliveries based on distance and time?
WITH VEHICLE AS (SELECT  VEHICLE_TYPE,
		COUNT(DELIVERY_ID) AS VEHICLES_COUNT,
		SUM(DISTANCE) AS TOTAL_DISTANCE,
        SUM(DELIVERY_TIME) AS TOTAL_TIME_IN_MINS
FROM DELIVERIES 
WHERE DELIVERY_STATUS = 'DELIVERED'
GROUP BY VEHICLE_TYPE)
		SELECT  VEHICLE_TYPE,VEHICLES_COUNT,
		ROUND((TOTAL_DISTANCE/TOTAL_TIME_IN_MINS)*1000,2) AS METERS_COVERED_BY_VEHICLE_IN_1_MIN
		FROM VEHICLE
        GROUP BY VEHICLE_TYPE
        ORDER BY METERS_COVERED_BY_VEHICLE_IN_1_MIN DESC;
        
-- Electric Bikes demonstrate the highest delivery efficiency, covering 787 meters per minute on average

-- 15.What percentage of deliveries are completed within the estimated delivery time?
SELECT * FROM DELIVERIES;
SELECT ROUND(SUM(CASE WHEN DELIVERY_TIME < ESTIMATED_TIME THEN 1
		ELSE 0 END) * 100.0/ COUNT(*),2) AS FAST_DELIVERY_PERCENTAGE
		FROM DELIVERIES
		WHERE DELIVERY_STATUS = 'DELIVERED';

-- Fast delivery percentage is 64.36 which was impressive

-- 16.How does monthly revenue trend over time and what months show significant growth or decline?
WITH MONTHLY_REVENUE AS(
SELECT  MONTH(ORDER_DATE) AS MONTH_NUMBER,
		MONTHNAME(ORDER_DATE) AS MONTH_NAME,
        ROUND(SUM(TOTAL_AMOUNT),2) AS REVENUE
FROM ORDERS
WHERE STATUS = 'DELIVERED'
GROUP BY MONTH_NUMBER,MONTH_NAME
)
SELECT  MONTH_NUMBER,MONTH_NAME,REVENUE,
		LAG(REVENUE)OVER(ORDER BY MONTH_NUMBER) AS PREVIOUS_NUMBER,
        ROUND((REVENUE - LAG(REVENUE)OVER(ORDER BY MONTH_NUMBER)),2) AS DIFFERENCE,
        ROUND((REVENUE-LAG(REVENUE) OVER(ORDER BY MONTH_NUMBER))
        /(LAG(REVENUE)OVER(ORDER BY MONTH_NUMBER))*100,2) AS GROWTH_PERECENTAGE
FROM MONTHLY_REVENUE;
-- July month major growth in revenue apporx.71% increase in the revenue
-- Wherever february and June got approx. 30% dip in the revenee
-- January,July and August have most of the revenue 

-- 17. How much revenue is lost because of cancelled or unsuccessful orders?
SELECT  STATUS,COUNT(ORDER_ID) AS ORDER_COUNT,
		ROUND(SUM(TOTAL_AMOUNT),2) AS REVENUE
FROM ORDERS
WHERE STATUS <> 'DELIVERED'
GROUP BY STATUS
ORDER BY REVENUE DESC ;

-- 18.What is the impact of discounts on customer spending behavior?
SELECT  CASE WHEN DISCOUNT_APPLIED BETWEEN 0 AND 10 THEN '0-10'
			 WHEN DISCOUNT_APPLIED BETWEEN 11 AND 20 THEN '11-20'
			 WHEN DISCOUNT_APPLIED BETWEEN 21 AND 30 THEN '21-30'
			 WHEN DISCOUNT_APPLIED BETWEEN 31 AND 40 THEN '31-40'
			 ELSE '41-50'
			 END AS DISCOUNT_BUCKET,
			 COUNT(*) AS TOTAL_ORDERS,
			 ROUND(AVG(TOTAL_AMOUNT)/COUNT(*),2) AS AVG_ORDER_VALUE
			FROM ORDERS
			WHERE STATUS = 'DELIVERED'
			GROUP BY DISCOUNT_BUCKET
			ORDER BY DISCOUNT_BUCKET;


-- 19.Which payment methods are associated with the highest average order values?
SELECT * FROM ORDERS;
SELECT PAYMENT_MODE,COUNT(*) AS ORDER_COUNT,
ROUND(SUM(TOTAL_AMOUNT),2) AS ORDER_AMOUNT,
ROUND(SUM(TOTAL_AMOUNT)/COUNT(*),2) AS AVERAGE_ORDER_PRICE,
ROUND(SUM(TOTAL_AMOUNT)/(SELECT SUM(TOTAL_AMOUNT) FROM ORDERS
WHERE STATUS = 'DELIVERED'),2)*100 AS PERCENTAGE  FROM ORDERS
WHERE STATUS = 'DELIVERED'
GROUP BY PAYMENT_MODE
ORDER BY PERCENTAGE DESC;

-- 20. Customer Lifetime Value (CLV) Ranking
SELECT * FROM ORDERS;
WITH REVENUE AS
		(SELECT  C.CUSTOMER_ID AS CUSTOMER_ID,C.NAME AS CUSTOMER_NAME,
		COUNT(O.ORDER_ID) AS ORDERS_COUNT,
        SUM(O.TOTAL_AMOUNT) AS REVENUE
        FROM CUSTOMERS C JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
        WHERE O.STATUS = 'DELIVERED'
        GROUP BY C.CUSTOMER_ID,C.NAME
        ORDER BY REVENUE DESC)
		SELECT CUSTOMER_ID,CUSTOMER_NAME,
        ORDERS_COUNT,REVENUE,
        DENSE_RANK()OVER(ORDER BY REVENUE DESC) AS CLV_RANK
        FROM REVENUE
        ORDER BY CLV_RANK ;
        
-- 21.Identify the top 20% of customers contributing approximately 80% of total revenue (Pareto Analysis).
SELECT * FROM CUSTOMERS;
WITH REVENUE AS (
		SELECT  C.CUSTOMER_ID AS CUSTOMER_ID,C.NAME AS CUSTOMER_NAME,
				SUM(O.TOTAL_AMOUNT) AS TOTAL_AMOUNT,
				COUNT(O.ORDER_ID) AS ORDERS_COUNT
				FROM ORDERS O JOIN CUSTOMERS C ON O.CUSTOMER_ID=C.CUSTOMER_ID
				WHERE O.STATUS = 'DELIVERED'
				GROUP BY  C.CUSTOMER_ID,C.NAME
				ORDER BY TOTAL_AMOUNT DESC,
						 ORDERS_COUNT DESC),
SUM AS(	SELECT  CUSTOMER_NAME,CUSTOMER_ID,TOTAL_AMOUNT,
				SUM(TOTAL_AMOUNT) OVER(ORDER BY TOTAL_AMOUNT DESC) AS CUMMUTATIVE_SUM,
                SUM(TOTAL_AMOUNT)OVER() AS TOTAL_REVENUE
                FROM REVENUE 
                GROUP BY CUSTOMER_NAME,CUSTOMER_ID
                ORDER BY TOTAL_AMOUNT DESC)
  SELECT        CUSTOMER_NAME,CUSTOMER_ID,TOTAL_AMOUNT,
				ROUND((TOTAL_AMOUNT / TOTAL_REVENUE)*100,2) AS REVENUE_PERCENT,
                ROUND((CUMMUTATIVE_SUM / TOTAL_REVENUE)*100,2) AS CUMMUTATIVE_PERCENT
                FROM SUM
                WHERE ROUND((CUMMUTATIVE_SUM / TOTAL_REVENUE)*100,2) <= 80.00
				ORDER BY TOTAL_AMOUNT DESC;





















